### ISSUE TITLE
Adding variable to directly specify Steam executable location

### ISSUE THREAD

**Issue by kekanzek** [cyberrumor/ammo#56] opened 2024-05-07 23:13 UTC
If it's possible, could you please add some sort of config where the Steam library paths can be set by the user? For example, I have a non-Steam Skyrim copy in my Steam library, and it's stored in a different path.

Thank you in advance

**Comment by cyberrumor** [comment] 2024-05-08 00:41
Hello, would you mind checking out this and see if it does what you need?

https://github.com/cyberrumor/ammo/issues/42#issuecomment-1987053442

**Comment by kekanzek** [comment] 2024-05-09 23:13
> Hello, would you mind checking out this and see if it does what you need?
> 
> [#42 (comment)](https://github.com/cyberrumor/ammo/issues/42#issuecomment-1987053442)

Can't check ATM, will check later, thanks

**Comment by cyberrumor** [comment] 2024-09-21 22:49
Closing as duplicate of https://github.com/cyberrumor/ammo/issues/42

**Closed by cyberrumor** 2024-09-21 22:49 UTC
